### ISSUE TITLE
Missing entry in the $lang array (referenced by resetPass method)

### ISSUE THREAD

**Issue by extendmarketing** [PHPAuth/PHPAuth#66] opened 2015-08-26 15:26 UTC
The following entry, referenced by the `resetPass` method in the `Auth` class seems to be missing from the `$lang` array: 

`$lang['newpassword_match']`

**Comment by Conver** [comment] 2015-08-27 21:22
Which language file are you using?

**Comment by cuonic** [comment] 2015-08-29 14:27
Duplicate of #58, which was fixed with commit 926775b. Try updating to the latest version ?

**Closed by cuonic** 2015-08-29 14:27 UTC
Labels: duplicate
