### ISSUE TITLE
deleteAttempts : Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error

### ISSUE THREAD

**Issue by soldiertt** [PHPAuth/PHPAuth#108] opened 2015-09-16 18:58 UTC
Hi,

I think i found an issue in the deleteAttemps method.
When i try to login multiple times with a wrong username/password, it calls login method that calls isblocked method that call deleteAttemps method.
At first try, it's ok at second try i receive this stacktrace :

	<br />
	<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: 	General error' in /opt/lampp/htdocs/burningphoenixteam/lib/PHPAuth/auth.class.php:1219
	Stack trace:
	#0 /opt/lampp/htdocs/burningphoenixteam/lib/PHPAuth/auth.class.php(1219): PDOStatement-&gt;fetch(2)
	#1 /opt/lampp/htdocs/burningphoenixteam/lib/PHPAuth/auth.class.php(1156): PHPAuth\Auth-&gt;deleteAttempts('188.44.66.193', false)
	#2 /opt/lampp/htdocs/burningphoenixteam/lib/PHPAuth/auth.class.php(47): PHPAuth\Auth-&gt;isBlocked()
	#3 /opt/lampp/htdocs/burningphoenixteam/auth/login.php(14): PHPAuth\Auth-&gt;login('dsfqfdff', 'fdsf', false)
	#4 {main}
	thrown in <b>/opt/lampp/htdocs/burningphoenixteam/lib/PHPAuth/auth.class.php</b> on line 	<b>1219</b><br />

I'm not sure but maybe it's because the $query variable first a select query and then is modified in the loop with a delete query.

thank you for fixing

**Comment by bugada** [comment] 2015-09-16 22:34
I can't reproduce the error. Can you give us more details? Can you post logs after updating the class with latest commits? Thank you.

**Comment by bugada** [comment] 2015-09-17 17:39
It has been fixed with #112. Can you confirm soldiertt?

**Comment by soldiertt** [comment] 2015-09-18 18:35
i confirm, it's fixed, thank you

**Comment by bugada** [comment] 2015-09-18 19:14
Please close this issue since it has been fixed. Thank you.

**Closed** 2015-09-18 19:37 UTC
