### ISSUE TITLE
Rememberme doesn't work + fix?

### ISSUE THREAD

**Issue by glowdemon1** [PHPAuth/PHPAuth#169] opened 2015-12-28 15:16 UTC
Noticed this when all of my users would always get remembered for atleast a month, even when the 'remember me' box was not checked. I dug into the code and found this snippet:
```
		if($remember == true) {
			$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_remember));
			$data['expiretime'] = strtotime($data['expire']);
		} else {
			$data['expire'] = date("Y-m-d H:i:s", strtotime($this->config->cookie_remember));
			$data['expiretime'] = 0;
		}
```

Notice that this snippet uses cookie_remember for both values. Shouldn't the bottom one be renamed to cookie_forget? Assuming you also want the session deleted when it's set to not remember a session.

**Comment by cuonic** [comment] 2015-12-28 17:05
This is a duplicate of #166 which was fixed with commit d3c499c1e17f4780f3e13dfe69d7ab614d9632b9

**Closed by cuonic** 2015-12-28 17:05 UTC
